### ISSUE TITLE
Task execution behaviour when execution time exceeds the re-execution period time.

### ISSUE THREAD

**Issue by pintarj** [kibertoad/toad-scheduler#114]
There are situations where one (long running) task exceeds in execution time the re-execution period time. This leads to the situation where a task is re-executed before the previous execution has terminated. 

One could predilige many behaviours in this cases:
- simply start a task execution concurrently (current behaviour?)
- wait the previous task's execution to terminate before (instantly) re-executing the task (queuing task's executions)
- skip a new execution and just complete the current task's execution

Is there any way to perform those kind of behaviours within this package? Am I missing something?

I would eventually be willing to implement it.

**Comment by kibertoad** [comment]
I will investigate and get back to you on this.

**Comment by pvince** [comment]
I was running into a similar problem. I kinda hacked around the problem by doing the following:
1. Set 'runImmediately' to false
2. When a task starts to execute, 'stop' the job.
3. When the task finishes, 'start' the job

I would second that it would be nice if there was an option on a job configuration to essentially pause the job's timer while a task is executing.

**Comment by fatihpense** [comment]
@pvince Great workaround! I confirm this method works, and I agree I would prefer the option included in the library.

**Comment by kibertoad** [comment]
Sorry for taking so long, but 2.0.0 has built-in parameter `preventOverrun` for jobs now.
