### ISSUE TITLE
Question: Is it possible to target a specific job to stop rather than to stop the whole scheduler?

### ISSUE THREAD

**Issue by jenseneducation-mattias-von-vogelsang** [kibertoad/toad-scheduler#12]
```
const { ToadScheduler, SimpleIntervalJob, AsyncTask } = require('toad-scheduler')

const scheduler = new ToadScheduler()

const task = new AsyncTask(
    'simple task', 
    () => { return db.pollForSomeData().then((result) => { /* continue the promise chain */ }) },
    (err: Error) => { /* handle error here */ }
)
const job = new SimpleIntervalJob({ seconds: 20, }, task)

scheduler.addSimpleIntervalJob(job)

// when stopping your app
scheduler.stop()
```

New to toad-scheduler. Is there a way to target a specific job, for termination? scheduler.stop() seems to end all running jobs.

**Comment by kibertoad** [comment]
@jenseneducation-mattias-von-vogelsang There is a `.stop()` method on job itself, would that suffice?

**Comment by jenseneducation-mattias-von-vogelsang** [comment]
Sounds very promising. Could you be so kind to give an example on usage? Ideally I want to be able to terminate the task from the tasks error handler.

**Comment by kibertoad** [comment]
E. g.:

```
const { ToadScheduler, SimpleIntervalJob, AsyncTask } = require('toad-scheduler')

const scheduler = new ToadScheduler()

const task = new AsyncTask(
    'simple task', 
    () => { return db.pollForSomeData().then((result) => { /* continue the promise chain */ }) },
    (err: Error) => { /* handle error here */ }
)
const job = new SimpleIntervalJob({ seconds: 20, }, task)

scheduler.addSimpleIntervalJob(job)

// stopping specific job
job.stop()
```

It is not possible to stop job from the task, by design, because task is a child of job, and as such is not aware of its existence.
Would it help if I exposed  a method on a scheduler that would allow to stop a job by id?

**Comment by jenseneducation-mattias-von-vogelsang** [comment]
Thank you kindly for your example. Unfortunately It would not help me in my use case. 

I would like that very much, it would fit my specific use case perfectly.

**Comment by kibertoad** [comment]
will release a new version later tonight

**Comment by jenseneducation-mattias-von-vogelsang** [comment]
Thank you kindly for your implementation. I'll try it out tomorrow. Closing this.

**Comment by kibertoad** [comment]
@jenseneducation-mattias-von-vogelsang Just published 1.1.0

**Comment by jenseneducation-mattias-von-vogelsang** [comment]
@kibertoad Awesome. I just got home, I'll implement it in my code.

**Comment by jenseneducation-mattias-von-vogelsang** [comment]
@kibertoad I tried to push a branch for a PR on fastify-schedule to bump toad-scheduler to 1.2 but got a 403. Could you bump it or give me temporary write access to push the branch?

**Comment by kibertoad** [comment]
@jenseneducation-mattias-von-vogelsang Isn't usual GitHub flow to fork a repository and then create a PR from that fork? Also since fastify-schedule doesn't come with package-lock, I believe updating locally should be sufficient.

**Comment by jenseneducation-mattias-von-vogelsang** [comment]
Ah! My bad, I'm new to "contributing" to open source.
I'll do it locally. Thanks!
