### ISSUE TITLE
Check if job exists or not without throw error

### ISSUE THREAD

**Issue by jonasostrom** [kibertoad/toad-scheduler#155]
Hi,

Would it be possible to have jobExists or that getById not throwing errors?

**Comment by kibertoad** [comment]
sure!

**Comment by kibertoad** [comment]
@jonasostrom 2.1.0 is out, could you please give it a try and report back?

**Comment by kibertoad** [comment]
@jonasostrom Any updates from your side? Does the new functionality work for you?
