### ISSUE TITLE
Run Job after another job has been run

### ISSUE THREAD

**Issue by faulander** [kibertoad/toad-scheduler#158]
How would i do that - or how could i change the queue order of the jobs?

**Comment by kibertoad** [comment]
@faulander There is no queue. Toad scheduler executes scheduled jobs on a periodic basis with given cadency automatically, you just need to set the frequency.

Maybe you could explain your use-case a little bit?

**Comment by faulander** [comment]
Yes, i am well aware of that. I have two task, which periodically run after 24hr. They are also set to run at startup (runImmediately = true), but the first needs to run before the 2nd, which it doesn't - no matter what i do.
i have changed the script to initially call the tasks manually and set "runImmediately" to false, but i though maybe there's another way to force a task to run before another.

**Comment by kibertoad** [comment]
There is no built-in task hierarchy and no guarantee about which one executes first.
Do those tasks need to be two separate tasks? Maybe you can simply combine them into same task, if their cadence is the same.
Alternatively, you can use https://www.npmjs.com/package/redis-semaphore or just in-memory flag (if you are not running in a distributed environment) for checking if previous task already executed, and if not, either sleep, or skip the execution entirely.

**Comment by faulander** [comment]
true, these could actually be one task, but i like to keep my code clean and separated. they have a different purpose. I will look into the flag-solution or otherwise stick with my current one.
thanks for the reply!
