### ISSUE TITLE
Scheduler status

### ISSUE THREAD

**Issue by viniciusnazario** [kibertoad/toad-scheduler#16]
Hello there. First, I'd like to thank for this package, help me a lot of.

Is there any to check the status of the schedule?
Thanks...

**Comment by kibertoad** [comment]
Thank you for kind words!
Could you please clarify what do you mean by "status"?

**Comment by viniciusnazario** [comment]
Hey, thank you very much for the quick response. Regarding the status issue, I need to inform the user if the schedule is running, stopped or started now.

**Comment by kibertoad** [comment]
Gotcha. Will take a look tomorrow and see if api there could be improved. Do you need to be able to retrieve this info by id?

**Comment by viniciusnazario** [comment]
In my case, only one schedule will run. So I guess it doesn't have to be by id.
Thank you very much for your help, I'm waiting, thanks.

**Comment by kibertoad** [comment]
Released in 1.3.0
