### ISSUE TITLE
preventOverrun seems to be non-working

### ISSUE THREAD

**Issue by jating1** [kibertoad/toad-scheduler#175]
I have this code, but with passing preventOverrun as true it is still starting a new job when the old job was running. Is it a bug in code or i am doing anything wrong ?

```
const task = new Task('Scheduler Task', () => {
        const startTime = new Date();
        const endTime = new Date();
        endTime.setTime(startTime.getTime() + SCHEDULER_INTERVAL * 60 * 1000);
        id = `NotificationScheduler: ${endTime} - Thread ${thread}`;
        logger.info(`Scheduler Task Triggered with ID: ${id}`);
        // My service logic
        this.notificationService.scheduleNotifications(endTime);
      });

      const job = new SimpleIntervalJob(
        {
          seconds: 10,
          runImmediately: true,
        },
        task,
        {
          id: 'id_1',
          preventOverrun: true,
        },
      );

      scheduler.addSimpleIntervalJob(job);
```

**Comment by kibertoad** [comment]
It looks like you should be using an AsyncTask, because `this.notificationService.scheduleNotifications(endTime);` seems asynchronous.

**Comment by jating1** [comment]
Yes, after using AsyncTask it seems to work. It is not running new job at every 10 seconds but still it start new job after 60-70 seconds. Do we have some default timeout or any other check we need to mention while using `preventOverrun` ?

**Comment by kibertoad** [comment]
ToadScheduler doesn't have built-in timeouts, you can add them using Promise.race manually. Don't forget to cancel them out, though, to avoid memory leaks. Like this: https://github.com/lokalise/node-service-template/blob/main/src/utils/timeoutUtils.ts

Perhaps I should add this logic into the lib
