### ISSUE TITLE
Does using the same ID for the Task and Job objects create problems?

### ISSUE THREAD

**Issue by hi-brylle** [kibertoad/toad-scheduler#177]
Here I'm using the same `task_id` string for the Task id and in the Job options. Is this alright? Thanks :)
```
start_sol_a_task = (ds_port_function: () => {}) => {
        const task_id = "dispense_solution_A"
        const task = new Task(task_id, ds_port_function)
        const job = new SimpleIntervalJob(
            { hours: 24, runImmediately: true }, 
            task,
            { id: task_id, preventOverrun: true })
        this.toad_scheduler.addSimpleIntervalJob(job)
    }
```

**Comment by raliqala** [comment]
Hi  
No it won't cause any problems, when you use the task_id on the task it is used as a task name, the on the job it is a job id they don't collide as far as I know.

**Comment by kibertoad** [comment]
Yes, this should work fine, they are used in completely different contexts.
