### ISSUE TITLE
How can I retrieve the TaskId or JobId in the handler?

### ISSUE THREAD

**Issue by Extend-Apps** [kibertoad/toad-scheduler#179]
I'd like to know what task or job is being executed in the handler.  Is that possible?

**Comment by Extend-Apps** [comment]
### Objective:  
When a task is 'kicked' off based on the schedule, we'd like to know details about what task and job are actually running.
### Goal:
Using the taskid and jobid, we can create a map of tasks (taskid -> function) that accept a certain set of values (jobId -> jobDetails) to execute.  In other words, we can retrieve job parameter values (ie. database) using the jobId, and pass those values in function (ie. function will be identified by the taskid).
### Solution:
see Pull Request  #180

**Comment by kibertoad** [comment]
@Extend-Apps one question - wouldn't it be more convenient to be able to pass freeform metadata parameter as a part of task creation, to make the parameter lookup unnecessary? or these can be dynamic and change by the time task fires?

**Comment by Extend-Apps** [comment]
In my use case, job parameters can change dynamically, and outside the schedule.  A process can modify the parameters between job runs.

**Comment by Extend-Apps** [comment]
For a use case where those parameters don't change, well they could be stored in a dictionary.  Same affect

**Comment by kibertoad** [comment]
@Extend-Apps Released in 2.3.0, please give it a try and let me know if it works as expected!
