### ISSUE TITLE
Start job immediately

### ISSUE THREAD

**Issue by KensingtonTech** [kibertoad/toad-scheduler#27]
Thanks for the great library!  I'd like to request a feature, namely the option to start a job immediately rather than at the end of the specified interval.  Cheers

**Comment by kibertoad** [comment]
Released in 1.4.0

**Comment by KensingtonTech** [comment]
Thanks @kibertoad

**Comment by kibertoad** [comment]
@KensingtonTech Can you test the feature and report back if it works as expected?

**Comment by KensingtonTech** [comment]
@kibertoad I already have, actually.  It's working as expected.
