### ISSUE TITLE
Question: Is there a way to destroy jobs?

### ISSUE THREAD

**Issue by samimsu** [kibertoad/toad-scheduler#34]
Currently I can stop jobs by their id but I want to destroy the job so that I can create a new job with the same id.

**Comment by kibertoad** [comment]
@samimsu I don't think this is currently possible. Can you explain your use-case a bit? Why is it not possible to reuse same job?

**Comment by samimsu** [comment]
I'm scheduling jobs based on command inputs for a Discord bot. The inputs may change so I want to be able to replace the old job.

**Comment by kibertoad** [comment]
Gotcha. Let me take a swing at it.

**Comment by kibertoad** [comment]
@samimsu Released in 1.5.0
