### ISSUE TITLE
Add id example in documentation

### ISSUE THREAD

**Issue by kpotschi** [kibertoad/toad-scheduler#49]
I'm super happy to make a PR and include an example if you want me to. Just took me 30 minutes to figure out how IDs work unfortunately.

**Comment by kibertoad** [comment]
@kpotschi Ping?

**Comment by kpotschi** [comment]
hey igor. check the Pull Request, i wrote something up :) #50

**Comment by kibertoad** [comment]
@kpotschi Thanks, totally missed it! Wrote few suggestions, please check it out :)
