### ISSUE TITLE
Insert In DB On Error of AsyncTask

### ISSUE THREAD

**Issue by iamsid** [kibertoad/toad-scheduler#54]
I am using AsyncTask to make an API call on schedule.
Regular API calls are working fine, and inserting an entry into the DB as "success" using Knex.

But, when user inputs an invalid URL, node-fetch throws an error, which is caught by the AsyncTask error handler.
At this point, I would like to log this error in the DB as well. But the knex.insert function being asyncronous, its failing to execute on the syncronous error handler function. This is what I have understood the issue is.

```
(err) => {
                console.log("HERE");

                knex('syncs_logs')
                    .insert({
                        id: item.id,
                        status_code: err,
                        error_datetime: dayjs.utc().format("YYYY-MM-DD HH:mm:ss"),
                        err_msg: JSON.stringify(err)
                    });
            }
```

Can you please help?

**Comment by kibertoad** [comment]
@iamsid Can you share complete example?

Shouldn't AsyncTask error handler work here? See example in the readme:
```
const task = new AsyncTask(
    'simple task', 
    () => { return db.pollForSomeData().then((result) => { /* continue the promise chain */ }) },
    (err: Error) => { /* handle error here */ }
)
```

**Comment by kibertoad** [comment]
Oh, wait, I see what you mean, error handler itself is synchronous. Let me try to come up with something.

**Comment by kibertoad** [comment]
@iamsid PR is up, please review!
