### ISSUE TITLE
Cron support

### ISSUE THREAD

**Issue by kibertoad** [kibertoad/toad-scheduler#60]
We should at least consider implementing cron support for those who need it, so that toad-scheduler could be used for wider set of cases.

**Comment by outbackStack** [comment]
could we please have this feature added? :-)

**Comment by outbackStack** [comment]
I would like it to run at a certain day of the week and at certain time when the server is not so busy.

**Comment by kibertoad** [comment]
sure, I'll give it a shot!

**Comment by michalis-woess-valcome** [comment]
From [node-schedule](https://github.com/node-schedule/node-schedule):

> While you can easily bend it to your will, if you only want to do something like "run this function every 5 minutes", toad-scheduler would be a better choice. But if you want to, say, "run this function at the :20 and :50 of every hour on the third Tuesday of every month," you'll find that Node Schedule suits your needs better. Additionally, Node Schedule has Windows support, unlike true cron, since the node runtime is now fully supported.

**Comment by kibertoad** [comment]
Cron support was released in 2.2.0

**Comment by outbackStack** [comment]
Thank you @kibertoad ! You are the best :-)
