### ISSUE TITLE
Error Code `P1001` Meaning?

### ISSUE THREAD

**Issue by Weswwn** [kibertoad/toad-scheduler#76]
Hi, 

Ran into an issue with the scheduler crashing. It logged an error code of `P1001.` Does anybody know what this means? 

Thanks

**Comment by kibertoad** [comment]
@Weswwn Could you share whole stacktrace?

**Comment by Weswwn** [comment]
Let me take a look and I'll paste it here once I get it. Thanks!

**Comment by Weswwn** [comment]
Ohh yes, thanks for the catch. I didn't realize the error was coming from Prisma. How did you know?

**Comment by ohager** [comment]
> Ohh yes, thanks for the catch. I didn't realize the error was coming from Prisma. How did you know?

I use prisma heavily (awesome piece of tech)...

**Comment by Weswwn** [comment]
@ohager Gotcha, thanks for leaving a message about it. I also really like Prisma ORM. Will close this topic out.
